### ISSUE TITLE
Set up project website

### ISSUE THREAD

**Issue by Zxun2** [AY2223S2-CS2103T-W12-1/tp#1]
Follow instructions in the [Documentation guide page](https://nus-cs2103-ay2223s2.github.io/tp/Documentation.html) of AB3 developer guide. When set up correctly, your project website should be available via the URL https://ay2223s2-{team-id}.github.io/tp e.g., https://ay2223s2-cs2103-w13-1.github.io/tp.

Go `settings` > `Pages` > Select `Deploy from branch` and target the `/docs` folder > Save

**Comment by wz2k** [comment]
Good work
