### ISSUE TITLE
Storing age in FriendlyLink may be a feature flaw

### ISSUE THREAD

**Issue by gohyongjing** [AY2223S2-CS2103T-W12-1/tp#129]
Currently, age of the person is stored in FriendlyLink.

This makes it very troublesome for users, since age need to be updated yearly

Let's keep the date of birth of each person instead of their age.

**Comment by heeeyi** [comment]
We can just use year of birth

**Comment by Zxun2** [comment]
We don't check how old the elderly is (Feature flaw) -- add to documentation

**Comment by wz2k** [comment]
Resolved by #158
