### ISSUE TITLE
[PE-D][Tester C] Unpair command auto-detection

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W12-1/tp#229]
When trying out the unpair command, I realised that trying to manually type out the command shows that it is invalid.

![Screenshot 2023-03-31 at 14.33.15.png](https://raw.githubusercontent.com/edures888/ped/main/files/cdee3677-03d6-4441-b83b-0d970934c034.png)

However, fully typing out the prefix `vic` seems to clear the issue.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: edures888/ped#4

**Comment by Zxun2** [comment]
Thanks for spotting this.
