### ISSUE TITLE
[PE-D][Tester D] Shortcuts: Ctrl+Z Does NOT Work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W12-1/tp#231]
![GIF 2023-03-31 14-46-48.gif](https://raw.githubusercontent.com/salty-flower/ped/main/files/a06f939f-6f64-4e17-be7a-afef5f683710.gif)
(Hit Ctrl+Z many many times after executing the command)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: salty-flower/ped#8

**Comment by Zxun2** [comment]
# Solution 

remove shortcuts
