### ISSUE TITLE
Create a team PR to [nus-cs2103-AY2223S2/tp] master branch.

### ISSUE THREAD

**Issue by Zxun2** [AY2223S2-CS2103T-W12-1/tp#7]
Follow the format:

**PR name**: `[Team ID] Product Name` e.g., `[CS2103-T09-2] InsureList`. As you merge code to your team repo's master branch, this PR will auto-update to reflect how much your team's product has progressed.

**PR subject**: the name of your product e.g., [CS2103-T09-2] InsureList 

**Description**: a 1-2 sentence overview (plain text only, no formatting or links) of your project indicating the target user and the value proposition e.g., InsureList helps insurance agents manage detail of their clients. It is optimized for CLI users so that frequent tasks can be done faster by typing in commands.

**Comment by Zxun2** [comment]
@AY2223S2-CS2103T-W12-1/developers anyone wants to take up this issue?

**Comment by gohyongjing** [comment]
I have created a PR

**Comment by gohyongjing** [comment]
![Uploading image.png…]()
