### ISSUE TITLE
There is a new commit in the upstream repo

### ISSUE THREAD

**Issue by damithc** [AY2223S2-CS2103T-W12-1/tp#9]
Folks, good to see you've forked the tP repo already.
Just to let you know, there is a new commit https://github.com/nus-cs2103-AY2223S2/tp/commit/928f14660452b529512dfcaa90f459ecdb744dca in the upstream repo in case you want to sync your fork with the latest upstream repo

**Comment by Zxun2** [comment]
Noted! @damithc
